### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by teenie-quaggard** [FAC-Sixteen/gph#19]
I know you have whiteboarded your schema, but it's a bit hard for an outsider (or for your future self!) to understand what's going on here:

![Screen Shot 2019-04-12 at 10 29 14](https://user-images.githubusercontent.com/37771591/56027396-e3d73280-5d0d-11e9-9ae5-26e3522af29d.png)

Just wanted to give you a heads up, that in the future you might consider using a schema generator online. Here's an example of one that I made in the past (sorry, I can't remember which generator we used 🤨).

![68747470733a2f2f692e696d6775722e636f6d2f4c55454c3450362e706e67](https://user-images.githubusercontent.com/37771591/56027563-331d6300-5d0e-11e9-8241-5e0daeb7f713.png)

**Comment by bantek89** [comment]
added to the readme
