### ISSUE TITLE
Very small readme issue

### ISSUE THREAD

**Issue by teenie-quaggard** [FAC-Sixteen/gph#26]
Don't forget to include your Heroku link in your readme and not just in the project header. When you fork these projects later, it'll make it easier for employers to check out the project. I nearly missed the Heroku link in the beginning!

![Screen Shot 2019-04-12 at 10 58 42](https://user-images.githubusercontent.com/37771591/56029263-f8b5c500-5d11-11e9-96ea-fbb0e64fc4f3.png)

**Comment by bantek89** [comment]
good spot, thank you! added now :)
